application: adabunny
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js 
  static_dir: js

- url: /css 
  static_dir: css

- url: /images 
  static_dir: images

- url: /.* 
  static_files : index.html 
  upload: index.html

- url: /.* 
  static_files : products.html 
  upload: products.html 

- url: /.* 
  static_files : contact.html 
  upload: contact.html 
